apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-agent
  labels:
    app: dev-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-agent
  template:
    metadata:
      labels:
        app: dev-agent
    spec:
      containers:
      - name: dev-agent
        image: dev-agent:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DEV_AGENT_REDIS_URL
          value: "redis://redis:6379"
        - name: DEV_AGENT_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: dev-agent-secret
              key: jwt-secret
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: dev-agent
spec:
  selector:
    app: dev-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-agent-secret
stringData:
  jwt-secret: "dev-secret-key"
